### ISSUE TITLE
Installation docs could be improved 

### ISSUE THREAD

**Issue by sigurasg** [mohe2015/AuthManagerOAuth#24]
First of all thanks for writing this plugin - it looks like it's exactly what I need for my self-hosted homelab Wiki :). However, as a PHP and MediaWiki n00b, I'm having a little trouble parsing the installation instructions. The [installation instructions](https://www.mediawiki.org/wiki/Extension:AuthManagerOAuth#Installation) say "Download and place the file(s) in a directory called AuthManagerOAuth in your extensions/ folder", but they don't say which files. It would be great if the instructions referenced which files, or e.g. gave a couple of command lines like 

wget ....zip; unzip *

or some such. I'm sure I'll figure it out with an hour's work or so...

**Comment by mohe2015** [comment]
@sigurasg I missed this github notification, sorry. I think the text there is automatically created using a template. I tried doing some small improvements to the template settings.

Can't check right now but it should be

```bash
cd extensions
git clone https://github.com/mohe2015/AuthManagerOAuth
cd AuthManagerOAuth
composer install --no-dev

# add the following or similar to LocalSettings.php
# require_once "$IP/extensions/AuthManagerOAuth/AuthManagerOAuth.php";
# and configure the settings like on the wiki

# Do the database update like on https://www.mediawiki.org/wiki/Manual:Update.php

```

**Comment by mohe2015** [comment]
Currently I don't provide prebuilt archives (for security reasons and because it's currently not worth the effort in my opinion) so this could definitely be improved.

**Comment by mohe2015** [comment]
Instead of the `git clone ...` you can probably also do
```
wget https://github.com/mohe2015/AuthManagerOAuth/archive/refs/heads/main.zip
unzip main.zip
```

**Comment by sigurasg** [comment]
Thanks - I'll poke at this on the weekend.

**Comment by mohe2015** [comment]
I've now created built artifacts and attached them to the release of v0.2.0. The steps now should be like on the wiki:
```
cd extensions
wget https://github.com/mohe2015/AuthManagerOAuth/releases/download/v0.2.0/AuthManagerOAuth.zip
unzip AuthManagerOAuth.zip

# add the following or similar to LocalSettings.php
# wfLoadExtension( 'AuthManagerOAuth' );
# and configure the settings like on the wiki

# Do the database update like on https://www.mediawiki.org/wiki/Manual:Update.php
```

**Comment by mohe2015** [comment]
I'll close this for now. Feel free to still answer and I will reopen it then.
